name: Build NOVA APK

# ───────────────────────────────────────────────────────────────
# Se dispara en cada push o pull-request a main
# y también manualmente desde el botón “Run workflow”.
# ───────────────────────────────────────────────────────────────
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar el repositorio
      - name: Checkout source
        uses: actions/checkout@v4

      # 2) Instalar JDK 17 (requerido por el Android Gradle Plugin)
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Instalar el SDK de Android (build-tools, platforms, etc.)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # 4) Instalar Gradle 8.4 (sin wrapper en el repo)
      - name: Setup Gradle 8.4
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      # 5) Compilar la variante Debug (APK ya firmado con la debug-keystore)
      - name: Build Debug APK
        run: gradle :app:assembleDebug --no-daemon --stacktrace

      # 6) Subir como artefacto para descargarlo desde “Actions”
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nova-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error     # Falla el job si no existe el APK
          retention-days: 7            # Opcional: días que se guarda el artefac
