name: Build NOVA APK

# ────────────────────────────────────────────────
# Disparadores del workflow
# ────────────────────────────────────────────────
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona tu repositorio
      - uses: actions/checkout@v4

      # 2) Prepara JDK 17 (requerido por AGP 8)
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Instala el SDK de Android (platform-tools, build-tools, etc.)
      - uses: android-actions/setup-android@v2

      # 4) Descarga Gradle 8.4 para usarlo sólo en este run
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      # 5) Genera el wrapper dentro de la carpeta NOVA
      - name: Generate Gradle Wrapper
        working-directory: NOVA            # <─ carpeta donde está settings.gradle.kts
        run: |
          gradle wrapper --gradle-version 8.4
          chmod +x ./gradlew

      # 6) Compila el APK Debug con el wrapper recién creado
      - name: Build Debug APK
        working-directory: NOVA            # <─ misma carpeta
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

      # 7) Publica el APK como artefacto descargable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nova-debug-apk
          path: NOVA/app/build/outputs/apk/debug/*.apk   # <─ ruta exacta del APK
          if-no-files-found: error
          retention-days: 7
